-- ============================================================================
-- SCHEMA GROUP 2: Content Graph & Creator Videos
-- TMDB cache, communities, creator videos + all counters, reactions, comments
-- ============================================================================

-- ── TMDB Titles Cache ─────────────────────────────────────────────────────────

CREATE TABLE public.titles (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tmdb_id      INT UNIQUE NOT NULL,
  media_type   TEXT NOT NULL REFERENCES public.media_types(value),
  title        TEXT NOT NULL,
  overview     TEXT,
  poster_url   TEXT,
  backdrop_url TEXT,
  release_date DATE,
  popularity   NUMERIC,
  vote_average NUMERIC,
  genre_ids    INT[],
  created_at   TIMESTAMPTZ DEFAULT now(),
  updated_at   TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_titles_tmdb       ON public.titles(tmdb_id);
CREATE INDEX idx_titles_popularity ON public.titles(popularity DESC NULLS LAST);
CREATE INDEX idx_titles_media_type ON public.titles(media_type);
CREATE INDEX idx_titles_release    ON public.titles(release_date DESC NULLS LAST);

CREATE TRIGGER handle_titles_updated_at
  BEFORE UPDATE ON public.titles FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime(updated_at);

ALTER TABLE public.titles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read titles"  ON public.titles FOR SELECT USING (true);
CREATE POLICY "Admins manage titles" ON public.titles FOR ALL USING (public.is_admin_or_reviewer());

-- ── Title Similarities ────────────────────────────────────────────────────────

CREATE TABLE public.title_similarities (
  title_id         UUID NOT NULL REFERENCES public.titles(id) ON DELETE CASCADE,
  similar_title_id UUID NOT NULL REFERENCES public.titles(id) ON DELETE CASCADE,
  score            NUMERIC(5,4) DEFAULT 0,
  PRIMARY KEY (title_id, similar_title_id),
  CHECK (title_id != similar_title_id)
);

CREATE INDEX idx_similarities_score ON public.title_similarities(title_id, score DESC);

ALTER TABLE public.title_similarities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read similarities" ON public.title_similarities FOR SELECT USING (true);

-- ── People & Cast ─────────────────────────────────────────────────────────────

CREATE TABLE public.people (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tmdb_person_id INT UNIQUE,
  name           TEXT NOT NULL,
  profile_url    TEXT,
  created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_people_tmdb ON public.people(tmdb_person_id);

ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read people" ON public.people FOR SELECT USING (true);

CREATE TABLE public.title_cast (
  title_id       UUID NOT NULL REFERENCES public.titles(id) ON DELETE CASCADE,
  person_id      UUID NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
  character_name TEXT,
  order_index    INT,
  PRIMARY KEY (title_id, person_id)
);

CREATE INDEX idx_cast_person ON public.title_cast(person_id);

ALTER TABLE public.title_cast ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read cast" ON public.title_cast FOR SELECT USING (true);

-- ── Streaming Platforms ───────────────────────────────────────────────────────

CREATE TABLE public.streaming_platforms (
  id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name     TEXT NOT NULL UNIQUE,
  slug     TEXT NOT NULL UNIQUE,
  logo_url TEXT
);

ALTER TABLE public.streaming_platforms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read platforms"   ON public.streaming_platforms FOR SELECT USING (true);
CREATE POLICY "Admins manage platforms" ON public.streaming_platforms FOR ALL USING (public.is_admin_or_reviewer());

CREATE TABLE public.title_streaming_availability (
  title_id      UUID NOT NULL REFERENCES public.titles(id) ON DELETE CASCADE,
  platform_id   UUID NOT NULL REFERENCES public.streaming_platforms(id) ON DELETE CASCADE,
  country_code  TEXT NOT NULL DEFAULT 'US',
  deep_link_url TEXT,
  web_url       TEXT,
  created_at    TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (title_id, platform_id, country_code)
);

CREATE INDEX idx_streaming_country ON public.title_streaming_availability(country_code);

ALTER TABLE public.title_streaming_availability ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read availability"   ON public.title_streaming_availability FOR SELECT USING (true);
CREATE POLICY "Admins manage availability" ON public.title_streaming_availability FOR ALL USING (public.is_admin_or_reviewer());

-- ── Communities ───────────────────────────────────────────────────────────────

CREATE TABLE public.communities (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_id          INT UNIQUE NOT NULL,
  title            TEXT NOT NULL,
  poster_path      TEXT,
  media_type       TEXT REFERENCES public.media_types(value),
  status           TEXT DEFAULT 'active' CHECK (status IN ('active', 'flagged', 'suspended')),
  toxicity_score   NUMERIC(5,2) DEFAULT 0,
  member_count     INT DEFAULT 0,
  post_count       INT DEFAULT 0,
  last_activity_at TIMESTAMPTZ DEFAULT now(),
  created_at       TIMESTAMPTZ DEFAULT now(),
  created_by       UUID REFERENCES auth.users(id)
);

CREATE INDEX idx_communities_member_count   ON public.communities(member_count DESC);
CREATE INDEX idx_communities_last_activity  ON public.communities(last_activity_at DESC);

ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read communities" ON public.communities FOR SELECT USING (true);
CREATE POLICY "Auth create communities" ON public.communities FOR INSERT WITH CHECK (auth.role() = 'authenticated');
-- FIX: removed the open FOR ALL UPDATE USING (true) policy — counter bumps now go
-- exclusively via the SECURITY DEFINER join_community/leave_community RPCs below.
CREATE POLICY "Admins manage communities" ON public.communities FOR UPDATE USING (public.is_admin_or_reviewer());

CREATE TABLE public.community_members (
  community_id BIGINT NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
  user_id      UUID   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role         TEXT   DEFAULT 'member' REFERENCES public.community_roles(value),
  joined_at    TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (community_id, user_id)
);

CREATE INDEX idx_community_members_user ON public.community_members(user_id);

ALTER TABLE public.community_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read members"      ON public.community_members FOR SELECT USING (true);
CREATE POLICY "Auth join communities"    ON public.community_members FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users leave communities"  ON public.community_members FOR DELETE  USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.join_community(p_show_id BIGINT)
RETURNS VOID AS $$
DECLARE v_uid UUID; v_comm_id BIGINT; v_new_member BOOLEAN := false;
BEGIN
  v_uid := auth.uid();
  SELECT id INTO v_comm_id FROM public.communities WHERE show_id = p_show_id;
  INSERT INTO public.community_members (community_id, user_id)
  VALUES (v_comm_id, v_uid) ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_new_member = ROW_COUNT;  -- TRUE only if row was inserted
  IF v_new_member THEN
    UPDATE public.communities SET member_count = member_count + 1 WHERE id = v_comm_id;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.leave_community(p_show_id BIGINT)
RETURNS VOID AS $$
DECLARE v_uid UUID; v_comm_id BIGINT;
BEGIN
  v_uid := auth.uid();
  SELECT id INTO v_comm_id FROM public.communities WHERE show_id = p_show_id;
  DELETE FROM public.community_members WHERE community_id = v_comm_id AND user_id = v_uid;
  IF FOUND THEN
    UPDATE public.communities SET member_count = GREATEST(member_count - 1, 0) WHERE id = v_comm_id;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── Community Posts ───────────────────────────────────────────────────────────

CREATE TABLE public.community_posts (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  community_id     BIGINT REFERENCES public.communities(id) ON DELETE CASCADE,
  show_id          INT,
  -- FIX: was nullable, enabling ghost/anonymous posts — now NOT NULL
  author_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content          TEXT,
  media_urls       TEXT[],
  media_types      TEXT[],
  hashtags         TEXT[],
  is_spoiler       BOOLEAN DEFAULT false,
  is_hidden        BOOLEAN DEFAULT false,
  is_locked        BOOLEAN DEFAULT false,   -- added in migration 21
  pinned_at        TIMESTAMPTZ,             -- added in migration 21
  score            INT DEFAULT 0,
  upvotes          INT DEFAULT 0,
  downvotes        INT DEFAULT 0,
  comment_count    INT DEFAULT 0,
  view_count       INT DEFAULT 0,
  deleted_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ DEFAULT now(),
  updated_at       TIMESTAMPTZ DEFAULT now(),
  last_activity_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_posts_community_created ON public.community_posts(community_id, created_at DESC);
CREATE INDEX idx_posts_author            ON public.community_posts(author_id);
CREATE INDEX idx_posts_score             ON public.community_posts(score DESC);
-- Added in migration 20260401000002
CREATE INDEX idx_posts_show_score        ON public.community_posts(show_id, score DESC);
CREATE INDEX idx_posts_show_comment_count ON public.community_posts(show_id, comment_count DESC);
CREATE INDEX idx_posts_show_created      ON public.community_posts(show_id, created_at DESC);

CREATE TRIGGER handle_posts_updated_at
  BEFORE UPDATE ON public.community_posts FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime(updated_at);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read posts"         ON public.community_posts FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Auth create posts"         ON public.community_posts FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Users update own posts"    ON public.community_posts FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Mods update posts"         ON public.community_posts FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM public.community_members cm
    WHERE cm.community_id = public.community_posts.community_id
      AND cm.user_id = auth.uid()
      AND cm.role IN ('moderator', 'admin')
  )
);
CREATE POLICY "Mods delete posts"         ON public.community_posts FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM public.community_members cm
    WHERE cm.community_id = public.community_posts.community_id
      AND cm.user_id = auth.uid()
      AND cm.role IN ('moderator', 'admin')
  )
);

-- ── Community Comments ────────────────────────────────────────────────────────

CREATE TABLE public.community_comments (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id    UUID NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
  -- FIX: nullable author_id retained to allow soft-delete ghost rows on CASCADE SET NULL
  author_id  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  content    TEXT,
  parent_id  UUID REFERENCES public.community_comments(id),
  upvotes    INT DEFAULT 0,
  downvotes  INT DEFAULT 0,
  is_hidden  BOOLEAN DEFAULT false,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_comments_post_created ON public.community_comments(post_id, created_at DESC);
CREATE INDEX idx_comments_parent       ON public.community_comments(parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX idx_comments_author       ON public.community_comments(author_id);

CREATE TRIGGER handle_comments_updated_at
  BEFORE UPDATE ON public.community_comments FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime(updated_at);

ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read comments" ON public.community_comments FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Auth create comments" ON public.community_comments FOR INSERT WITH CHECK (auth.uid() = author_id);

-- Comment count trigger
CREATE OR REPLACE FUNCTION public.handle_community_comment_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.community_posts SET comment_count = comment_count + 1 WHERE id = NEW.post_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.community_posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = OLD.post_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_community_comment_change
  AFTER INSERT OR DELETE ON public.community_comments
  FOR EACH ROW EXECUTE FUNCTION public.handle_community_comment_count();

-- ── Votes ─────────────────────────────────────────────────────────────────────

CREATE TABLE public.post_votes (
  user_id    UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id    UUID NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
  vote       INT NOT NULL CHECK (vote IN (1, -1)),
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

ALTER TABLE public.post_votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read post_votes"  ON public.post_votes FOR SELECT USING (true);
CREATE POLICY "Users vote on posts"     ON public.post_votes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users change post votes" ON public.post_votes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users remove post votes" ON public.post_votes FOR DELETE USING (auth.uid() = user_id);

CREATE TABLE public.comment_votes (
  user_id    UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  comment_id UUID NOT NULL REFERENCES public.community_comments(id) ON DELETE CASCADE,
  vote       INT NOT NULL CHECK (vote IN (1, -1)),
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, comment_id)
);

ALTER TABLE public.comment_votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read comment_votes"  ON public.comment_votes FOR SELECT USING (true);
CREATE POLICY "Users vote on comments"     ON public.comment_votes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users change comment votes" ON public.comment_votes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users remove comment votes" ON public.comment_votes FOR DELETE USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.vote_on_post(p_post_id UUID, p_vote INT)
RETURNS VOID AS $$
DECLARE
  v_uid UUID; v_current INT; v_new INT;
  v_up_d INT := 0; v_down_d INT := 0;
BEGIN
  v_uid := auth.uid();
  SELECT vote INTO v_current FROM public.post_votes WHERE user_id = v_uid AND post_id = p_post_id;
  IF v_current IS NULL THEN v_current := 0; END IF;
  v_new := CASE WHEN p_vote = v_current THEN 0 ELSE p_vote END;
  IF v_new = v_current THEN RETURN; END IF;
  IF v_current =  1 THEN v_up_d   := v_up_d   - 1; END IF;
  IF v_current = -1 THEN v_down_d := v_down_d - 1; END IF;
  IF v_new     =  1 THEN v_up_d   := v_up_d   + 1; END IF;
  IF v_new     = -1 THEN v_down_d := v_down_d + 1; END IF;
  IF v_new = 0 THEN
    DELETE FROM public.post_votes WHERE user_id = v_uid AND post_id = p_post_id;
  ELSE
    INSERT INTO public.post_votes (user_id, post_id, vote) VALUES (v_uid, p_post_id, v_new)
    ON CONFLICT (user_id, post_id) DO UPDATE SET vote = v_new, created_at = now();
  END IF;
  UPDATE public.community_posts SET
    upvotes = upvotes + v_up_d, downvotes = downvotes + v_down_d,
    score = score + (v_up_d - v_down_d), last_activity_at = now()
  WHERE id = p_post_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.vote_on_comment(p_comment_id UUID, p_vote INT)
RETURNS VOID AS $$
DECLARE
  v_uid UUID; v_current INT; v_new INT;
  v_up_d INT := 0; v_down_d INT := 0;
BEGIN
  v_uid := auth.uid();
  SELECT vote INTO v_current FROM public.comment_votes WHERE user_id = v_uid AND comment_id = p_comment_id;
  IF v_current IS NULL THEN v_current := 0; END IF;
  v_new := CASE WHEN p_vote = v_current THEN 0 ELSE p_vote END;
  IF v_new = v_current THEN RETURN; END IF;
  IF v_current =  1 THEN v_up_d   := v_up_d   - 1; END IF;
  IF v_current = -1 THEN v_down_d := v_down_d - 1; END IF;
  IF v_new     =  1 THEN v_up_d   := v_up_d   + 1; END IF;
  IF v_new     = -1 THEN v_down_d := v_down_d + 1; END IF;
  IF v_new = 0 THEN
    DELETE FROM public.comment_votes WHERE user_id = v_uid AND comment_id = p_comment_id;
  ELSE
    INSERT INTO public.comment_votes (user_id, comment_id, vote) VALUES (v_uid, p_comment_id, v_new)
    ON CONFLICT (user_id, comment_id) DO UPDATE SET vote = v_new, created_at = now();
  END IF;
  UPDATE public.community_comments SET
    upvotes = upvotes + v_up_d, downvotes = downvotes + v_down_d
  WHERE id = p_comment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── Creator Videos ────────────────────────────────────────────────────────────

CREATE TABLE public.creator_videos (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  creator_id               UUID NOT NULL CONSTRAINT creator_videos_creator_id_fkey REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Media
  video_url                TEXT NOT NULL,
  thumbnail_url            TEXT,
  -- FIX: duration_seconds is nullable because Mux reports real duration post-encode
  duration_seconds         INT CHECK (duration_seconds IS NULL OR duration_seconds > 0),
  aspect_ratio             TEXT DEFAULT '9:16',
  -- Mux HLS (added in migration 20260402120000)
  mux_asset_id             TEXT,
  mux_playback_id          TEXT,
  mux_status               TEXT DEFAULT 'processing'
    CHECK (mux_status IN ('processing','ready','errored')),
  mux_duration_seconds     NUMERIC,
  -- TMDB Linking
  tmdb_id                  INT,
  tmdb_type                TEXT CHECK (tmdb_type IS NULL OR tmdb_type IN ('movie', 'tv')),
  tmdb_title               TEXT,
  -- Metadata
  title                    TEXT,
  description              TEXT,
  tags                     TEXT[],
  spoiler                  BOOLEAN DEFAULT false,
  -- A/B testing
  alt_title                TEXT,
  alt_thumbnail_url        TEXT,
  -- Moderation
  status                   TEXT DEFAULT 'pending'
    CHECK (status IN ('pending','approved','rejected','removed','processing','ready')),
  moderation_flags         JSONB DEFAULT '{}',
  auto_quality_score       NUMERIC(5,4),
  report_count             INT DEFAULT 0,
  reviewed_by              UUID REFERENCES public.profiles(id),
  reviewed_at              TIMESTAMPTZ,
  rejection_reason         TEXT,
  -- Feed control
  suppress_until           TIMESTAMPTZ,
  boost_until              TIMESTAMPTZ DEFAULT (now() + interval '24 hours'),
  -- Counters (denormalized, maintained by triggers + flush_counter_events)
  view_count               INT DEFAULT 0,
  like_count               INT DEFAULT 0,
  comment_count            INT DEFAULT 0,
  share_count              INT DEFAULT 0,
  total_watch_time_seconds INT DEFAULT 0,
  avg_completion_pct       NUMERIC(5,4) DEFAULT 0 CHECK (avg_completion_pct BETWEEN 0 AND 1),
  -- Scoring
  engagement_score         NUMERIC(10,4) DEFAULT 0,
  quality_score            NUMERIC(10,4),
  -- Soft delete
  deleted_at               TIMESTAMPTZ,
  created_at               TIMESTAMPTZ DEFAULT now(),
  updated_at               TIMESTAMPTZ DEFAULT now()
);

-- Core indexes
CREATE INDEX idx_cv_creator         ON public.creator_videos(creator_id, created_at DESC);
CREATE INDEX idx_cv_status          ON public.creator_videos(status);
-- Hot-path feed index (partial, covering)
CREATE INDEX idx_cv_approved_score  ON public.creator_videos(engagement_score DESC)
  WHERE status = 'approved' AND deleted_at IS NULL;
CREATE INDEX idx_cv_ranked_feed     ON public.creator_videos(engagement_score DESC, created_at DESC)
  WHERE status = 'approved' AND deleted_at IS NULL;
CREATE INDEX idx_cv_creator_cursor  ON public.creator_videos(creator_id, created_at DESC, id)
  WHERE status = 'approved' AND deleted_at IS NULL;
CREATE INDEX idx_cv_tmdb            ON public.creator_videos(tmdb_id, tmdb_type) WHERE tmdb_id IS NOT NULL;
-- Moderation
CREATE INDEX idx_cv_moderation_queue ON public.creator_videos(created_at ASC)
  WHERE status = 'pending' AND deleted_at IS NULL;
CREATE INDEX idx_cv_reported        ON public.creator_videos(report_count DESC)
  WHERE report_count > 0 AND status = 'approved';
-- Mux webhook lookup
CREATE INDEX idx_cv_mux_playback    ON public.creator_videos(mux_playback_id) WHERE mux_playback_id IS NOT NULL;
-- GIN on tags
CREATE INDEX idx_cv_tags_gin        ON public.creator_videos USING GIN (tags)
  WHERE tags IS NOT NULL AND deleted_at IS NULL;

CREATE TRIGGER handle_cv_updated_at
  BEFORE UPDATE ON public.creator_videos FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime(updated_at);

ALTER TABLE public.creator_videos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public view approved videos" ON public.creator_videos FOR SELECT
  USING (status = 'approved' AND deleted_at IS NULL);
CREATE POLICY "Creators view own videos"    ON public.creator_videos FOR SELECT
  USING (auth.uid() = creator_id);
CREATE POLICY "Creators upload videos"      ON public.creator_videos FOR INSERT WITH CHECK (
  auth.uid() = creator_id AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'creator' AND creator_status = 'approved'
  )
);
CREATE POLICY "Creators update own pending" ON public.creator_videos FOR UPDATE
  USING (auth.uid() = creator_id AND status IN ('pending', 'rejected'));
CREATE POLICY "Creators delete own pending" ON public.creator_videos FOR DELETE
  USING (auth.uid() = creator_id AND status IN ('pending', 'rejected'));
CREATE POLICY "Admins view all videos"      ON public.creator_videos FOR SELECT
  USING (public.is_admin_or_reviewer());
CREATE POLICY "Admins moderate videos"      ON public.creator_videos FOR UPDATE
  USING (public.is_admin_or_reviewer());

-- ── Video Engagement Events (Partitioned) ─────────────────────────────────────

CREATE TABLE public.video_engagement_events (
  id                     UUID DEFAULT gen_random_uuid(),
  video_id               UUID NOT NULL REFERENCES public.creator_videos(id) ON DELETE CASCADE,
  user_id                UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  watch_duration_seconds INT NOT NULL CHECK (watch_duration_seconds >= 0),
  completion_pct         NUMERIC(5,4) NOT NULL CHECK (completion_pct BETWEEN 0 AND 1),
  created_at             TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Default catch-all + historical partitions
CREATE TABLE public.vee_default  PARTITION OF public.video_engagement_events DEFAULT;
CREATE TABLE public.vee_2025_02  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
CREATE TABLE public.vee_2025_03  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');
CREATE TABLE public.vee_2025_04  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE public.vee_2025_05  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE public.vee_2025_06  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');
CREATE TABLE public.vee_2025_07  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-07-01') TO ('2025-08-01');
CREATE TABLE public.vee_2025_08  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');
CREATE TABLE public.vee_2025_09  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');
CREATE TABLE public.vee_2025_10  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');
CREATE TABLE public.vee_2025_11  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');
CREATE TABLE public.vee_2025_12  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');
CREATE TABLE public.vee_2026_01  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE public.vee_2026_02  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE public.vee_2026_03  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE public.vee_2026_04  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE public.vee_2026_05  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE public.vee_2026_06  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE public.vee_2026_07  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE public.vee_2026_08  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE public.vee_2026_09  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE public.vee_2026_10  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE public.vee_2026_11  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE public.vee_2026_12  PARTITION OF public.video_engagement_events FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

CREATE INDEX idx_vee_video        ON public.video_engagement_events(video_id);
CREATE INDEX idx_vee_user         ON public.video_engagement_events(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_vee_created      ON public.video_engagement_events(created_at DESC);
CREATE INDEX idx_vee_video_created ON public.video_engagement_events(video_id, created_at DESC);

ALTER TABLE public.video_engagement_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Auth insert engagement"     ON public.video_engagement_events FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Users view own engagement"  ON public.video_engagement_events FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Creators view video stats"  ON public.video_engagement_events FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.creator_videos WHERE id = video_id AND creator_id = auth.uid())
);
CREATE POLICY "Admins view all engagement" ON public.video_engagement_events FOR SELECT USING (public.is_admin_or_reviewer());

-- ── Video Reactions ───────────────────────────────────────────────────────────

CREATE TABLE public.video_reactions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  video_id      UUID NOT NULL REFERENCES public.creator_videos(id) ON DELETE CASCADE,
  user_id       UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reaction_type TEXT NOT NULL REFERENCES public.reaction_types(value),
  created_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE(video_id, user_id)
);

CREATE INDEX idx_vr_user ON public.video_reactions(user_id);

ALTER TABLE public.video_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read reactions"     ON public.video_reactions FOR SELECT USING (true);
CREATE POLICY "Users react"               ON public.video_reactions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own reactions" ON public.video_reactions FOR UPDATE
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users unreact"             ON public.video_reactions FOR DELETE USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.handle_reaction_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.reaction_type = 'heart' THEN
    UPDATE public.creator_videos SET like_count = like_count + 1 WHERE id = NEW.video_id;
  ELSIF TG_OP = 'DELETE' AND OLD.reaction_type = 'heart' THEN
    UPDATE public.creator_videos SET like_count = GREATEST(like_count - 1, 0) WHERE id = OLD.video_id;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_reaction_change
  AFTER INSERT OR DELETE ON public.video_reactions
  FOR EACH ROW EXECUTE FUNCTION public.handle_reaction_count();

-- ── Video Comments ────────────────────────────────────────────────────────────

CREATE TABLE public.video_comments (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  video_id   UUID NOT NULL REFERENCES public.creator_videos(id) ON DELETE CASCADE,
  author_id  UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content    TEXT NOT NULL,
  parent_id  UUID REFERENCES public.video_comments(id) ON DELETE CASCADE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_vc_video_created ON public.video_comments(video_id, created_at DESC);
CREATE INDEX idx_vc_parent        ON public.video_comments(parent_id) WHERE parent_id IS NOT NULL;

CREATE TRIGGER handle_vc_updated_at
  BEFORE UPDATE ON public.video_comments FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime(updated_at);

ALTER TABLE public.video_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read video comments" ON public.video_comments FOR SELECT USING (deleted_at IS NULL);
CREATE POLICY "Users post comments"        ON public.video_comments FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Users delete own comments"  ON public.video_comments FOR DELETE USING (auth.uid() = author_id);

CREATE OR REPLACE FUNCTION public.handle_video_comment_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.creator_videos SET comment_count = comment_count + 1 WHERE id = NEW.video_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.creator_videos SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = OLD.video_id;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_video_comment_change
  AFTER INSERT OR DELETE ON public.video_comments
  FOR EACH ROW EXECUTE FUNCTION public.handle_video_comment_count();

-- ── Creator Video Reports ─────────────────────────────────────────────────────

CREATE TABLE public.creator_video_reports (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  video_id     UUID NOT NULL REFERENCES public.creator_videos(id) ON DELETE CASCADE,
  reporter_id  UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  reason       TEXT NOT NULL CHECK (reason IN (
    'inappropriate','harassment','spam','misinformation','copyright','violence','hate_speech','other'
  )),
  details      TEXT,
  status       TEXT DEFAULT 'pending' CHECK (status IN ('pending','reviewed','resolved','dismissed')),
  reviewed_by  UUID REFERENCES public.profiles(id),
  review_notes TEXT,
  reviewed_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE (video_id, reporter_id)
);

CREATE INDEX idx_cvr_video  ON public.creator_video_reports(video_id);
CREATE INDEX idx_cvr_status ON public.creator_video_reports(status);

ALTER TABLE public.creator_video_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users report videos"     ON public.creator_video_reports FOR INSERT WITH CHECK (auth.uid() = reporter_id);
CREATE POLICY "Users view own reports"  ON public.creator_video_reports FOR SELECT USING (reporter_id = auth.uid());
CREATE POLICY "Admins view all reports" ON public.creator_video_reports FOR SELECT USING (public.is_admin_or_reviewer());
CREATE POLICY "Admins update reports"   ON public.creator_video_reports FOR UPDATE USING (public.is_admin_or_reviewer());

-- Sync report_count and auto-suppress trigger
CREATE OR REPLACE FUNCTION public.sync_report_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.creator_videos
    SET report_count = report_count + 1
    WHERE id = NEW.video_id;

    IF (SELECT report_count FROM public.creator_videos WHERE id = NEW.video_id) >= 3 THEN
      UPDATE public.creator_videos
      SET suppress_until = GREATEST(COALESCE(suppress_until, now()), now() + interval '24 hours')
      WHERE id = NEW.video_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_video_report
  AFTER INSERT ON public.creator_video_reports
  FOR EACH ROW EXECUTE FUNCTION public.sync_report_count();

-- ── Hashtag System ────────────────────────────────────────────────────────────

CREATE TABLE public.hashtags (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tag            TEXT NOT NULL,
  tag_normalized TEXT NOT NULL UNIQUE,
  usage_count    INT DEFAULT 0,
  trending_score NUMERIC(10,4) DEFAULT 0,
  is_banned      BOOLEAN DEFAULT false,
  first_used_at  TIMESTAMPTZ DEFAULT now(),
  last_used_at   TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_ht_trending ON public.hashtags(trending_score DESC) WHERE NOT is_banned;
CREATE INDEX idx_ht_usage    ON public.hashtags(usage_count DESC) WHERE NOT is_banned;
CREATE INDEX idx_ht_search   ON public.hashtags USING GIN (tag_normalized extensions.gin_trgm_ops);

ALTER TABLE public.hashtags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read hashtags"   ON public.hashtags FOR SELECT USING (true);
CREATE POLICY "Admins manage hashtags" ON public.hashtags FOR ALL USING (public.is_admin_or_reviewer());

CREATE TABLE public.video_hashtags (
  video_id   UUID NOT NULL REFERENCES public.creator_videos(id) ON DELETE CASCADE,
  hashtag_id UUID NOT NULL REFERENCES public.hashtags(id) ON DELETE CASCADE,
  PRIMARY KEY (video_id, hashtag_id)
);

CREATE INDEX idx_vh_hashtag ON public.video_hashtags(hashtag_id);

ALTER TABLE public.video_hashtags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read video hashtags" ON public.video_hashtags FOR SELECT USING (true);

CREATE OR REPLACE FUNCTION public.sync_video_hashtags()
RETURNS TRIGGER AS $$
DECLARE
  raw_tag TEXT; clean_tag TEXT; ht_id UUID;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.tags IS NOT DISTINCT FROM OLD.tags THEN RETURN NEW; END IF;
  DELETE FROM public.video_hashtags WHERE video_id = NEW.id;
  IF TG_OP = 'UPDATE' AND OLD.tags IS NOT NULL THEN
    FOREACH raw_tag IN ARRAY OLD.tags LOOP
      clean_tag := lower(regexp_replace(raw_tag, '^#', ''));
      UPDATE public.hashtags SET usage_count = GREATEST(usage_count - 1, 0) WHERE tag_normalized = clean_tag;
    END LOOP;
  END IF;
  IF NEW.tags IS NOT NULL THEN
    FOREACH raw_tag IN ARRAY NEW.tags LOOP
      clean_tag := lower(regexp_replace(raw_tag, '^#', ''));
      IF length(clean_tag) < 2 THEN CONTINUE; END IF;
      INSERT INTO public.hashtags (tag, tag_normalized, usage_count, last_used_at)
      VALUES (raw_tag, clean_tag, 1, now())
      ON CONFLICT (tag_normalized) DO UPDATE SET usage_count = public.hashtags.usage_count + 1, last_used_at = now()
      RETURNING id INTO ht_id;
      INSERT INTO public.video_hashtags (video_id, hashtag_id) VALUES (NEW.id, ht_id) ON CONFLICT DO NOTHING;
    END LOOP;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_video_tags_change
  AFTER INSERT OR UPDATE OF tags ON public.creator_videos
  FOR EACH ROW EXECUTE FUNCTION public.sync_video_hashtags();

-- ── Trailer Interactions ──────────────────────────────────────────────────────

CREATE TABLE public.trailer_reactions (
  trailer_id TEXT NOT NULL,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (trailer_id, user_id)
);

CREATE INDEX idx_trailer_reactions_trailer_id ON public.trailer_reactions(trailer_id);
CREATE INDEX idx_trailer_reactions_user_id    ON public.trailer_reactions(user_id);

ALTER TABLE public.trailer_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view trailer reactions" ON public.trailer_reactions FOR SELECT USING (true);
CREATE POLICY "Users add own trailer reaction"    ON public.trailer_reactions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own trailer reaction" ON public.trailer_reactions FOR DELETE USING (auth.uid() = user_id);

CREATE TABLE public.trailer_comments (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trailer_id TEXT NOT NULL,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content    TEXT NOT NULL CHECK (char_length(trim(content)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_trailer_comments_trailer_id ON public.trailer_comments(trailer_id);
CREATE INDEX idx_trailer_comments_created_at ON public.trailer_comments(created_at DESC);

ALTER TABLE public.trailer_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view trailer comments"     ON public.trailer_comments FOR SELECT USING (true);
CREATE POLICY "Users add own trailer comment"        ON public.trailer_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own trailer comment"     ON public.trailer_comments FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Users update own trailer comment"     ON public.trailer_comments FOR UPDATE USING (auth.uid() = user_id);
