-- Migration to support waitlist gathering and support/deletion requests

-- ── Waitlist Emails Table ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.waitlist_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'invited', 'joined')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS for waitlist_emails
ALTER TABLE public.waitlist_emails ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert into waitlist_emails (anonymous waitlist signups)
DROP POLICY IF EXISTS "Allow anonymous waitlist signups" ON public.waitlist_emails;
CREATE POLICY "Allow anonymous waitlist signups" ON public.waitlist_emails 
    FOR INSERT 
    WITH CHECK (true);

-- Allow admins to read/manage waitlist
DROP POLICY IF EXISTS "Allow admins to manage waitlist" ON public.waitlist_emails;
CREATE POLICY "Allow admins to manage waitlist" ON public.waitlist_emails 
    FOR ALL 
    USING (public.is_admin_or_reviewer());


-- ── Support Requests Table ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.support_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS for support_requests
ALTER TABLE public.support_requests ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to insert into support_requests (contact form)
DROP POLICY IF EXISTS "Allow anonymous support requests" ON public.support_requests;
CREATE POLICY "Allow anonymous support requests" ON public.support_requests 
    FOR INSERT 
    WITH CHECK (true);

-- Allow admins to read/manage support requests
DROP POLICY IF EXISTS "Allow admins to manage support requests" ON public.support_requests;
CREATE POLICY "Allow admins to manage support requests" ON public.support_requests 
    FOR ALL 
    USING (public.is_admin_or_reviewer());
