-- ============================================================================
-- Fix: Create missing tables referenced by edge functions and RPC.
--
-- 1. user_video_views   — tracks which videos a user has already seen, used
--                         by get_edge_feed to deduplicate the feed.
-- 2. interaction_logs   — raw log of all video interaction events, written by
--                         the batch-interactions edge function.
-- 3. community_members.is_muted — boolean column to allow muting community
--                         notification noise without leaving the community.
-- ============================================================================

-- ── 1. user_video_views ───────────────────────────────────────────────────────
-- Simple seen-video log used by get_edge_feed to exclude re-watched videos.
-- Kept minimal and append-only; dedup happens in the RPC via NOT EXISTS.

CREATE TABLE IF NOT EXISTS public.user_video_views (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  video_id   UUID NOT NULL REFERENCES public.creator_videos(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Prevent duplicate rows for the same (user, video) pair within a session.
  -- Allow re-insertion after 7 days naturally (no unique constraint) so the
  -- RPC's "last 7 days" window works correctly over time.
  CONSTRAINT uq_user_video_views UNIQUE (user_id, video_id)
);

-- Index: the RPC filters by user_id + video_id + created_at window
CREATE INDEX IF NOT EXISTS idx_uvv_user_video_created
  ON public.user_video_views(user_id, video_id, created_at DESC);

ALTER TABLE public.user_video_views ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users insert own views"
  ON public.user_video_views FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users view own history"
  ON public.user_video_views FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins view all views"
  ON public.user_video_views FOR SELECT
  USING (public.is_admin_or_reviewer());

-- ── 2. interaction_logs ───────────────────────────────────────────────────────
-- Raw event log written by the batch-interactions edge function.
-- Stores per-video engagement actions (view, like, share, watch_time).

CREATE TABLE IF NOT EXISTS public.interaction_logs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        UUID    NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  video_id       UUID    NOT NULL REFERENCES public.creator_videos(id) ON DELETE CASCADE,
  action         TEXT    NOT NULL CHECK (action IN ('view', 'like', 'unlike', 'share', 'comment', 'watch_time', 'skip')),
  watch_time_ms  INT     CHECK (watch_time_ms IS NULL OR watch_time_ms >= 0),
  duration_ms    INT     CHECK (duration_ms   IS NULL OR duration_ms   > 0),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_il_user      ON public.interaction_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_il_video     ON public.interaction_logs(video_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_il_action    ON public.interaction_logs(action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_il_user_vid  ON public.interaction_logs(user_id, video_id, created_at DESC);

ALTER TABLE public.interaction_logs ENABLE ROW LEVEL SECURITY;

-- The batch-interactions edge function uses service role for inserts (bypasses RLS).
-- These SELECT policies allow creators and admins to inspect the raw data.
CREATE POLICY "Users view own interaction logs"
  ON public.interaction_logs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Creators view their video logs"
  ON public.interaction_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.creator_videos cv
      WHERE cv.id = video_id AND cv.creator_id = auth.uid()
    )
  );

CREATE POLICY "Admins view all logs"
  ON public.interaction_logs FOR SELECT
  USING (public.is_admin_or_reviewer());

-- ── 3. community_members.is_muted ────────────────────────────────────────────
-- Lets users mute notifications for a community without leaving it.

ALTER TABLE public.community_members
  ADD COLUMN IF NOT EXISTS is_muted BOOLEAN NOT NULL DEFAULT false;
