ALTER TABLE public.user_trust_scores
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS score NUMERIC(5,2) DEFAULT 50.0,
  ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'Bronze',
  ADD COLUMN IF NOT EXISTS calculated_at TIMESTAMPTZ DEFAULT now();
